-- ─────────────────────────────────────────────────────────────────────────
-- corecity Nigeria - Database Initialization Script
-- ─────────────────────────────────────────────────────────────────────────

CREATE DATABASE IF NOT EXISTS corecity_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE corecity_db;

-- ─── Users ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    phone       VARCHAR(20) NOT NULL UNIQUE,   -- Nigerian format: +234XXXXXXXXXX
    password    VARCHAR(255) NOT NULL,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    role        ENUM('BUYER','SELLER','AGENT','ADMIN') NOT NULL DEFAULT 'BUYER',
    nin         VARCHAR(11),                   -- National Identification Number
    bvn         VARCHAR(11),                   -- Bank Verification Number
    is_verified BOOLEAN DEFAULT FALSE,
    avatar_url  VARCHAR(500),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ─── States & LGAs (Nigerian) ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS states (
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS lgas (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    state_id INT NOT NULL,
    name     VARCHAR(100) NOT NULL,
    FOREIGN KEY (state_id) REFERENCES states(id)
);

-- ─── Properties ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS properties (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    property_type    ENUM('APARTMENT','BUNGALOW','DUPLEX','TERRACED','SEMI_DETACHED','DETACHED','LAND','COMMERCIAL') NOT NULL,
    listing_type     ENUM('FOR_SALE','FOR_RENT','SHORT_LET') NOT NULL,
    price            DECIMAL(15,2) NOT NULL,        -- in NGN (Naira)
    price_period     ENUM('OUTRIGHT','PER_YEAR','PER_MONTH','PER_NIGHT') DEFAULT 'OUTRIGHT',
    bedrooms         INT DEFAULT 0,
    bathrooms        INT DEFAULT 0,
    toilets          INT DEFAULT 0,
    size_sqm         DECIMAL(10,2),
    address          VARCHAR(500) NOT NULL,
    state_id         INT,
    lga_id           INT,
    latitude         DECIMAL(10,8),
    longitude        DECIMAL(11,8),
    owner_id         BIGINT NOT NULL,
    agent_id         BIGINT,
    status           ENUM('PENDING','ACTIVE','SOLD','RENTED','INACTIVE') DEFAULT 'PENDING',
    is_negotiable    BOOLEAN DEFAULT TRUE,
    amenities        JSON,                          -- e.g. ["BOREHOLE","GENERATOR","CCTV","GYM"]
    views_count      INT DEFAULT 0,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (state_id) REFERENCES states(id),
    FOREIGN KEY (lga_id) REFERENCES lgas(id)
);

-- ─── Property Images ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS property_files (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    property_id  BIGINT NOT NULL,
    file_url     VARCHAR(500) NOT NULL,
    file_type    ENUM('IMAGE','VIDEO','DOCUMENT','VIRTUAL_TOUR') DEFAULT 'IMAGE',
    is_primary   BOOLEAN DEFAULT FALSE,
    uploaded_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE
);

-- ─── Transactions (Paystack Integration) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS transactions (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    reference        VARCHAR(100) NOT NULL UNIQUE,  -- Paystack reference
    property_id      BIGINT NOT NULL,
    buyer_id         BIGINT NOT NULL,
    seller_id        BIGINT NOT NULL,
    amount           DECIMAL(15,2) NOT NULL,         -- in NGN
    service_fee      DECIMAL(15,2) NOT NULL DEFAULT 0,
    type             ENUM('RENT','PURCHASE','INSPECTION_FEE','AGENT_FEE') NOT NULL,
    status           ENUM('INITIATED','PENDING','SUCCESS','FAILED','REFUNDED') DEFAULT 'INITIATED',
    payment_channel  VARCHAR(50),                    -- card, bank_transfer, ussd
    paystack_data    JSON,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (property_id) REFERENCES properties(id),
    FOREIGN KEY (buyer_id) REFERENCES users(id),
    FOREIGN KEY (seller_id) REFERENCES users(id)
);

-- ─── Notifications ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    title      VARCHAR(255) NOT NULL,
    message    TEXT NOT NULL,
    type       ENUM('SYSTEM','TRANSACTION','PROPERTY','ENQUIRY','VERIFICATION') NOT NULL,
    channel    ENUM('IN_APP','EMAIL','SMS','PUSH') NOT NULL,
    is_read    BOOLEAN DEFAULT FALSE,
    meta       JSON,
    sent_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ─── Enquiries ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS enquiries (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    property_id  BIGINT NOT NULL,
    sender_id    BIGINT NOT NULL,
    message      TEXT NOT NULL,
    status       ENUM('NEW','READ','REPLIED') DEFAULT 'NEW',
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (property_id) REFERENCES properties(id),
    FOREIGN KEY (sender_id) REFERENCES users(id)
);

-- ─── Saved / Favourites ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS saved_properties (
    user_id     BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    saved_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, property_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (property_id) REFERENCES properties(id)
);

-- ─── Seed: Nigerian States ───────────────────────────────────────────────
INSERT INTO states (name) VALUES
('Abia'),('Adamawa'),('Akwa Ibom'),('Anambra'),('Bauchi'),('Bayelsa'),
('Benue'),('Borno'),('Cross River'),('Delta'),('Ebonyi'),('Edo'),
('Ekiti'),('Enugu'),('FCT - Abuja'),('Gombe'),('Imo'),('Jigawa'),
('Kaduna'),('Kano'),('Katsina'),('Kebbi'),('Kogi'),('Kwara'),
('Lagos'),('Nasarawa'),('Niger'),('Ogun'),('Ondo'),('Osun'),
('Oyo'),('Plateau'),('Rivers'),('Sokoto'),('Taraba'),('Yobe'),('Zamfara');

-- Seed all Nigerian LGAs (774 total)
INSERT INTO lgas (state_id, name) VALUES
(1,'Aba North'),
(1,'Aba South'),
(1,'Arochukwu'),
(1,'Bende'),
(1,'Ikwuano'),
(1,'Isiala Ngwa North'),
(1,'Isiala Ngwa South'),
(1,'Isuikwuato'),
(1,'Obi Ngwa'),
(1,'Ohafia'),
(1,'Osisioma Ngwa'),
(1,'Ugwunagbo'),
(1,'Ukwa East'),
(1,'Ukwa West'),
(1,'Umuahia North'),
(1,'Umuahia South'),
(1,'Umunneochi');

INSERT INTO lgas (state_id, name) VALUES
(2,'Demsa'),
(2,'Fufore'),
(2,'Ganye'),
(2,'Girei'),
(2,'Gombi'),
(2,'Guyuk'),
(2,'Hong'),
(2,'Jada'),
(2,'Lamurde'),
(2,'Madagali'),
(2,'Maiha'),
(2,'Mayo-Belwa'),
(2,'Michika'),
(2,'Mubi North'),
(2,'Mubi South'),
(2,'Numan'),
(2,'Shelleng'),
(2,'Song'),
(2,'Toungo'),
(2,'Yola North'),
(2,'Yola South');

INSERT INTO lgas (state_id, name) VALUES
(3,'Abak'),
(3,'Eastern Obolo'),
(3,'Eket'),
(3,'Esit Eket'),
(3,'Essien Udim'),
(3,'Etim Ekpo'),
(3,'Etinan'),
(3,'Ibeno'),
(3,'Ibesikpo Asutan'),
(3,'Ibiono Ibom'),
(3,'Ika'),
(3,'Ikono'),
(3,'Ikot Abasi'),
(3,'Ikot Ekpene'),
(3,'Ini'),
(3,'Itu'),
(3,'Mbo'),
(3,'Mkpat Enin'),
(3,'Nsit Atai'),
(3,'Nsit Ibom'),
(3,'Nsit Ubium'),
(3,'Obot Akara'),
(3,'Okobo'),
(3,'Onna'),
(3,'Oron'),
(3,'Oruk Anam'),
(3,'Udung Uko'),
(3,'Ukanafun'),
(3,'Uruan'),
(3,'Urue-Offong/Oruko'),
(3,'Uyo');

INSERT INTO lgas (state_id, name) VALUES
(4,'Aguata'),
(4,'Anambra East'),
(4,'Anambra West'),
(4,'Anaocha'),
(4,'Awka North'),
(4,'Awka South'),
(4,'Ayamelum'),
(4,'Dunukofia'),
(4,'Ekwusigo'),
(4,'Idemili North'),
(4,'Idemili South'),
(4,'Ihiala'),
(4,'Njikoka'),
(4,'Nnewi North'),
(4,'Nnewi South'),
(4,'Ogbaru'),
(4,'Onitsha North'),
(4,'Onitsha South'),
(4,'Orumba North'),
(4,'Orumba South'),
(4,'Oyi');

INSERT INTO lgas (state_id, name) VALUES
(5,'Alkaleri'),
(5,'Bauchi'),
(5,'Bogoro'),
(5,'Damban'),
(5,'Darazo'),
(5,'Dass'),
(5,'Gamawa'),
(5,'Ganjuwa'),
(5,'Giade'),
(5,'Itas/Gadau'),
(5,'Jama''are'),
(5,'Katagum'),
(5,'Kirfi'),
(5,'Misau'),
(5,'Ningi'),
(5,'Shira'),
(5,'Tafawa Balewa'),
(5,'Toro'),
(5,'Warji'),
(5,'Zaki');

INSERT INTO lgas (state_id, name) VALUES
(6,'Brass'),
(6,'Ekeremor'),
(6,'Kolokuma/Opokuma'),
(6,'Nembe'),
(6,'Ogbia'),
(6,'Sagbama'),
(6,'Southern Ijaw'),
(6,'Yenagoa');

INSERT INTO lgas (state_id, name) VALUES
(7,'Ado'),
(7,'Agatu'),
(7,'Apa'),
(7,'Buruku'),
(7,'Gboko'),
(7,'Guma'),
(7,'Gwer East'),
(7,'Gwer West'),
(7,'Katsina-Ala'),
(7,'Konshisha'),
(7,'Kwande'),
(7,'Logo'),
(7,'Makurdi'),
(7,'Obi'),
(7,'Ogbadibo'),
(7,'Ohimini'),
(7,'Oju'),
(7,'Okpokwu'),
(7,'Otukpo'),
(7,'Tarka'),
(7,'Ukum'),
(7,'Ushongo'),
(7,'Vandeikya');

INSERT INTO lgas (state_id, name) VALUES
(8,'Abadam'),
(8,'Askira/Uba'),
(8,'Bama'),
(8,'Bayo'),
(8,'Biu'),
(8,'Chibok'),
(8,'Damboa'),
(8,'Dikwa'),
(8,'Gubio'),
(8,'Guzamala'),
(8,'Gwoza'),
(8,'Hawul'),
(8,'Jere'),
(8,'Kaga'),
(8,'Kala/Balge'),
(8,'Konduga'),
(8,'Kukawa'),
(8,'Kwaya Kusar'),
(8,'Mafa'),
(8,'Magumeri'),
(8,'Maiduguri'),
(8,'Marte'),
(8,'Mobbar'),
(8,'Monguno'),
(8,'Ngala'),
(8,'Nganzai'),
(8,'Shani');

INSERT INTO lgas (state_id, name) VALUES
(9,'Abi'),
(9,'Akamkpa'),
(9,'Akpabuyo'),
(9,'Bakassi'),
(9,'Bekwarra'),
(9,'Biase'),
(9,'Boki'),
(9,'Calabar Municipal'),
(9,'Calabar South'),
(9,'Etung'),
(9,'Ikom'),
(9,'Obanliku'),
(9,'Obubra'),
(9,'Obudu'),
(9,'Odukpani'),
(9,'Ogoja'),
(9,'Yakurr'),
(9,'Yala');

INSERT INTO lgas (state_id, name) VALUES
(10,'Aniocha North'),
(10,'Aniocha South'),
(10,'Bomadi'),
(10,'Burutu'),
(10,'Ethiope East'),
(10,'Ethiope West'),
(10,'Ika North East'),
(10,'Ika South'),
(10,'Isoko North'),
(10,'Isoko South'),
(10,'Ndokwa East'),
(10,'Ndokwa West'),
(10,'Okpe'),
(10,'Oshimili North'),
(10,'Oshimili South'),
(10,'Patani'),
(10,'Sapele'),
(10,'Udu'),
(10,'Ughelli North'),
(10,'Ughelli South'),
(10,'Ukwuani'),
(10,'Uvwie'),
(10,'Warri North'),
(10,'Warri South'),
(10,'Warri South West');

INSERT INTO lgas (state_id, name) VALUES
(11,'Abakaliki'),
(11,'Afikpo North'),
(11,'Afikpo South'),
(11,'Ebonyi'),
(11,'Ezza North'),
(11,'Ezza South'),
(11,'Ikwo'),
(11,'Ishielu'),
(11,'Ivo'),
(11,'Izzi'),
(11,'Ohaozara'),
(11,'Ohaukwu'),
(11,'Onicha');

INSERT INTO lgas (state_id, name) VALUES
(12,'Akoko-Edo'),
(12,'Egor'),
(12,'Esan Central'),
(12,'Esan North-East'),
(12,'Esan South-East'),
(12,'Esan West'),
(12,'Etsako Central'),
(12,'Etsako East'),
(12,'Etsako West'),
(12,'Igueben'),
(12,'Ikpoba Okha'),
(12,'Orhionmwon'),
(12,'Oredo'),
(12,'Ovia North-East'),
(12,'Ovia South-West'),
(12,'Owan East'),
(12,'Owan West'),
(12,'Uhunmwonde');

INSERT INTO lgas (state_id, name) VALUES
(13,'Ado-Ekiti'),
(13,'Efon'),
(13,'Ekiti East'),
(13,'Ekiti South-West'),
(13,'Ekiti West'),
(13,'Emure'),
(13,'Gbonyin'),
(13,'Ido-Osi'),
(13,'Ijero'),
(13,'Ikere'),
(13,'Ikole'),
(13,'Ilejemeje'),
(13,'Irepodun/Ifelodun'),
(13,'Ise/Orun'),
(13,'Moba'),
(13,'Oye');

INSERT INTO lgas (state_id, name) VALUES
(14,'Aninri'),
(14,'Awgu'),
(14,'Enugu East'),
(14,'Enugu North'),
(14,'Enugu South'),
(14,'Ezeagu'),
(14,'Igbo Etiti'),
(14,'Igbo Eze North'),
(14,'Igbo Eze South'),
(14,'Isi Uzo'),
(14,'Nkanu East'),
(14,'Nkanu West'),
(14,'Nsukka'),
(14,'Oji River'),
(14,'Udenu'),
(14,'Udi'),
(14,'Uzo-Uwani');

INSERT INTO lgas (state_id, name) VALUES
(15,'Abaji'),
(15,'Abuja Municipal Area Council'),
(15,'Bwari'),
(15,'Gwagwalada'),
(15,'Kuje'),
(15,'Kwali');

INSERT INTO lgas (state_id, name) VALUES
(16,'Akko'),
(16,'Balanga'),
(16,'Billiri'),
(16,'Dukku'),
(16,'Funakaye'),
(16,'Gombe'),
(16,'Kaltungo'),
(16,'Kwami'),
(16,'Nafada'),
(16,'Shongom'),
(16,'Yamaltu/Deba');

INSERT INTO lgas (state_id, name) VALUES
(17,'Aboh Mbaise'),
(17,'Ahiazu Mbaise'),
(17,'Ehime Mbano'),
(17,'Ezinihitte'),
(17,'Ideato North'),
(17,'Ideato South'),
(17,'Ihitte/Uboma'),
(17,'Ikeduru'),
(17,'Isiala Mbano'),
(17,'Isu'),
(17,'Mbaitoli'),
(17,'Ngor Okpala'),
(17,'Njaba'),
(17,'Nkwerre'),
(17,'Nwangele'),
(17,'Obowo'),
(17,'Oguta'),
(17,'Ohaji/Egbema'),
(17,'Okigwe'),
(17,'Orlu'),
(17,'Orsu'),
(17,'Oru East'),
(17,'Oru West'),
(17,'Owerri Municipal'),
(17,'Owerri North'),
(17,'Owerri West'),
(17,'Unuimo');

INSERT INTO lgas (state_id, name) VALUES
(18,'Auyo'),
(18,'Babura'),
(18,'Birnin Kudu'),
(18,'Birniwa'),
(18,'Buji'),
(18,'Dutse'),
(18,'Gagarawa'),
(18,'Garki'),
(18,'Gumel'),
(18,'Guri'),
(18,'Gwaram'),
(18,'Gwiwa'),
(18,'Hadejia'),
(18,'Jahun'),
(18,'Kafin Hausa'),
(18,'Kaugama'),
(18,'Kazaure'),
(18,'Kiri Kasama'),
(18,'Kiyawa'),
(18,'Maigatari'),
(18,'Malam Madori'),
(18,'Miga'),
(18,'Ringim'),
(18,'Roni'),
(18,'Sule Tankarkar'),
(18,'Taura'),
(18,'Yankwashi');

INSERT INTO lgas (state_id, name) VALUES
(19,'Birnin Gwari'),
(19,'Chikun'),
(19,'Giwa'),
(19,'Igabi'),
(19,'Ikara'),
(19,'Jaba'),
(19,'Jema''a'),
(19,'Kachia'),
(19,'Kaduna North'),
(19,'Kaduna South'),
(19,'Kagarko'),
(19,'Kajuru'),
(19,'Kaura'),
(19,'Kauru'),
(19,'Kubau'),
(19,'Kudan'),
(19,'Lere'),
(19,'Makarfi'),
(19,'Sabon Gari'),
(19,'Sanga'),
(19,'Soba'),
(19,'Zangon Kataf'),
(19,'Zaria');

INSERT INTO lgas (state_id, name) VALUES
(20,'Ajingi'),
(20,'Albasu'),
(20,'Bagwai'),
(20,'Bebeji'),
(20,'Bichi'),
(20,'Bunkure'),
(20,'Dala'),
(20,'Dambatta'),
(20,'Dawakin Kudu'),
(20,'Dawakin Tofa'),
(20,'Doguwa'),
(20,'Fagge'),
(20,'Gabasawa'),
(20,'Garko'),
(20,'Garun Mallam'),
(20,'Gaya'),
(20,'Gezawa'),
(20,'Gwale'),
(20,'Gwarzo'),
(20,'Kabo'),
(20,'Kano Municipal'),
(20,'Karaye'),
(20,'Kibiya'),
(20,'Kiru'),
(20,'Kumbotso'),
(20,'Kunchi'),
(20,'Kura'),
(20,'Madobi'),
(20,'Makoda'),
(20,'Minjibir'),
(20,'Nasarawa'),
(20,'Rano'),
(20,'Rimin Gado'),
(20,'Rogo'),
(20,'Shanono'),
(20,'Sumaila'),
(20,'Takai'),
(20,'Tarauni'),
(20,'Tofa'),
(20,'Tsanyawa'),
(20,'Tudun Wada'),
(20,'Ungogo'),
(20,'Warawa'),
(20,'Wudil');

INSERT INTO lgas (state_id, name) VALUES
(21,'Bakori'),
(21,'Batagarawa'),
(21,'Batsari'),
(21,'Baure'),
(21,'Bindawa'),
(21,'Charanchi'),
(21,'Dandume'),
(21,'Danja'),
(21,'Dan Musa'),
(21,'Daura'),
(21,'Dutsi'),
(21,'Dutsin-Ma'),
(21,'Faskari'),
(21,'Funtua'),
(21,'Ingawa'),
(21,'Jibia'),
(21,'Kafur'),
(21,'Kaita'),
(21,'Kankara'),
(21,'Kankia'),
(21,'Katsina'),
(21,'Kurfi'),
(21,'Kusada'),
(21,'Mai''Adua'),
(21,'Malumfashi'),
(21,'Mani'),
(21,'Mashi'),
(21,'Matazu'),
(21,'Musawa'),
(21,'Rimi'),
(21,'Sabuwa'),
(21,'Safana'),
(21,'Sandamu'),
(21,'Zango');

INSERT INTO lgas (state_id, name) VALUES
(22,'Aleiro'),
(22,'Arewa Dandi'),
(22,'Argungu'),
(22,'Augie'),
(22,'Bagudo'),
(22,'Birnin Kebbi'),
(22,'Bunza'),
(22,'Dandi'),
(22,'Fakai'),
(22,'Gwandu'),
(22,'Jega'),
(22,'Kalgo'),
(22,'Koko/Besse'),
(22,'Maiyama'),
(22,'Ngaski'),
(22,'Sakaba'),
(22,'Shanga'),
(22,'Suru'),
(22,'Wasagu/Danko'),
(22,'Yauri'),
(22,'Zuru');

INSERT INTO lgas (state_id, name) VALUES
(23,'Adavi'),
(23,'Ajaokuta'),
(23,'Ankpa'),
(23,'Bassa'),
(23,'Dekina'),
(23,'Ibaji'),
(23,'Idah'),
(23,'Igalamela Odolu'),
(23,'Ijumu'),
(23,'Kabba/Bunu'),
(23,'Kogi'),
(23,'Lokoja'),
(23,'Mopa Muro'),
(23,'Ofu'),
(23,'Ogori/Magongo'),
(23,'Okehi'),
(23,'Okene'),
(23,'Olamaboro'),
(23,'Omala'),
(23,'Yagba East'),
(23,'Yagba West');

INSERT INTO lgas (state_id, name) VALUES
(24,'Asa'),
(24,'Baruten'),
(24,'Edu'),
(24,'Ekiti'),
(24,'Ifelodun'),
(24,'Ilorin East'),
(24,'Ilorin South'),
(24,'Ilorin West'),
(24,'Irepodun'),
(24,'Isin'),
(24,'Kaiama'),
(24,'Moro'),
(24,'Offa'),
(24,'Oke Ero'),
(24,'Oyun'),
(24,'Pategi');

INSERT INTO lgas (state_id, name) VALUES
(25,'Agege'),
(25,'Ajeromi-Ifelodun'),
(25,'Alimosho'),
(25,'Amuwo-Odofin'),
(25,'Apapa'),
(25,'Badagry'),
(25,'Epe'),
(25,'Eti-Osa'),
(25,'Ibeju/Lekki'),
(25,'Ifako-Ijaye'),
(25,'Ikeja'),
(25,'Ikorodu'),
(25,'Kosofe'),
(25,'Lagos Island'),
(25,'Lagos Mainland'),
(25,'Mushin'),
(25,'Ojo'),
(25,'Oshodi-Isolo'),
(25,'Shomolu'),
(25,'Surulere');

INSERT INTO lgas (state_id, name) VALUES
(26,'Akwanga'),
(26,'Awe'),
(26,'Doma'),
(26,'Karu'),
(26,'Keana'),
(26,'Keffi'),
(26,'Kokona'),
(26,'Lafia'),
(26,'Nasarawa'),
(26,'Nasarawa Egon'),
(26,'Obi'),
(26,'Toto'),
(26,'Wamba');

INSERT INTO lgas (state_id, name) VALUES
(27,'Agaie'),
(27,'Agwara'),
(27,'Bida'),
(27,'Borgu'),
(27,'Bosso'),
(27,'Chanchaga'),
(27,'Edati'),
(27,'Gbako'),
(27,'Gurara'),
(27,'Katcha'),
(27,'Kontagora'),
(27,'Lapai'),
(27,'Lavun'),
(27,'Magama'),
(27,'Mariga'),
(27,'Mashegu'),
(27,'Mokwa'),
(27,'Munya'),
(27,'Paikoro'),
(27,'Rafi'),
(27,'Rijau'),
(27,'Shiroro'),
(27,'Suleja'),
(27,'Tafa'),
(27,'Wushishi');

INSERT INTO lgas (state_id, name) VALUES
(28,'Abeokuta North'),
(28,'Abeokuta South'),
(28,'Ado-Odo/Ota'),
(28,'Egbado North'),
(28,'Egbado South'),
(28,'Ewekoro'),
(28,'Ifo'),
(28,'Ijebu East'),
(28,'Ijebu North'),
(28,'Ijebu North East'),
(28,'Ijebu Ode'),
(28,'Ikenne'),
(28,'Imeko Afon'),
(28,'Ipokia'),
(28,'Obafemi Owode'),
(28,'Odeda'),
(28,'Odogbolu'),
(28,'Ogun Waterside'),
(28,'Remo North'),
(28,'Shagamu');

INSERT INTO lgas (state_id, name) VALUES
(29,'Akoko North East'),
(29,'Akoko North West'),
(29,'Akoko South East'),
(29,'Akoko South West'),
(29,'Akure North'),
(29,'Akure South'),
(29,'Ese Odo'),
(29,'Idanre'),
(29,'Ifedore'),
(29,'Ilaje'),
(29,'Ile Oluji/Okeigbo'),
(29,'Irele'),
(29,'Odigbo'),
(29,'Okitipupa'),
(29,'Ondo East'),
(29,'Ondo West'),
(29,'Ose'),
(29,'Owo');

INSERT INTO lgas (state_id, name) VALUES
(30,'Aiyedade'),
(30,'Aiyedire'),
(30,'Atakunmosa East'),
(30,'Atakunmosa West'),
(30,'Boluwaduro'),
(30,'Boripe'),
(30,'Ede North'),
(30,'Ede South'),
(30,'Egbedore'),
(30,'Ejigbo'),
(30,'Ife Central'),
(30,'Ife East'),
(30,'Ife North'),
(30,'Ife South'),
(30,'Ifedayo'),
(30,'Ifelodun'),
(30,'Ila'),
(30,'Ilesa East'),
(30,'Ilesa West'),
(30,'Irepodun'),
(30,'Irewole'),
(30,'Isokan'),
(30,'Iwo'),
(30,'Obokun'),
(30,'Odo Otin'),
(30,'Ola Oluwa'),
(30,'Olorunda'),
(30,'Oriade'),
(30,'Orolu'),
(30,'Osogbo');

INSERT INTO lgas (state_id, name) VALUES
(31,'Afijio'),
(31,'Akinyele'),
(31,'Atiba'),
(31,'Atisbo'),
(31,'Egbeda'),
(31,'Ibadan North'),
(31,'Ibadan North-East'),
(31,'Ibadan North-West'),
(31,'Ibadan South-East'),
(31,'Ibadan South-West'),
(31,'Ibarapa Central'),
(31,'Ibarapa East'),
(31,'Ibarapa North'),
(31,'Ido'),
(31,'Irepo'),
(31,'Iseyin'),
(31,'Itesiwaju'),
(31,'Iwajowa'),
(31,'Kajola'),
(31,'Lagelu'),
(31,'Ogbomosho North'),
(31,'Ogbomosho South'),
(31,'Ogo Oluwa'),
(31,'Olorunsogo'),
(31,'Oluyole'),
(31,'Ona Ara'),
(31,'Orelope'),
(31,'Ori Ire'),
(31,'Oyo East'),
(31,'Oyo West'),
(31,'Saki East'),
(31,'Saki West'),
(31,'Surulere');

INSERT INTO lgas (state_id, name) VALUES
(32,'Barkin Ladi'),
(32,'Bassa'),
(32,'Bokkos'),
(32,'Jos East'),
(32,'Jos North'),
(32,'Jos South'),
(32,'Kanam'),
(32,'Kanke'),
(32,'Langtang North'),
(32,'Langtang South'),
(32,'Mangu'),
(32,'Mikang'),
(32,'Pankshin'),
(32,'Qua''an Pan'),
(32,'Riyom'),
(32,'Shendam'),
(32,'Wase');

INSERT INTO lgas (state_id, name) VALUES
(33,'Abua/Odual'),
(33,'Ahoada East'),
(33,'Ahoada West'),
(33,'Akuku-Toru'),
(33,'Andoni'),
(33,'Asari-Toru'),
(33,'Bonny'),
(33,'Degema'),
(33,'Eleme'),
(33,'Emuoha'),
(33,'Etche'),
(33,'Gokana'),
(33,'Ikwerre'),
(33,'Khana'),
(33,'Obio/Akpor'),
(33,'Ogba/Egbema/Ndoni'),
(33,'Ogu/Bolo'),
(33,'Okrika'),
(33,'Omuma'),
(33,'Opobo/Nkoro'),
(33,'Oyigbo'),
(33,'Port Harcourt'),
(33,'Tai');

INSERT INTO lgas (state_id, name) VALUES
(34,'Binji'),
(34,'Bodinga'),
(34,'Dange Shuni'),
(34,'Gada'),
(34,'Goronyo'),
(34,'Gudu'),
(34,'Gwadabawa'),
(34,'Illela'),
(34,'Isa'),
(34,'Kebbe'),
(34,'Kware'),
(34,'Rabah'),
(34,'Sabon Birni'),
(34,'Shagari'),
(34,'Silame'),
(34,'Sokoto North'),
(34,'Sokoto South'),
(34,'Tambuwal'),
(34,'Tangaza'),
(34,'Tureta'),
(34,'Wamako'),
(34,'Wurno'),
(34,'Yabo');

INSERT INTO lgas (state_id, name) VALUES
(35,'Ardo Kola'),
(35,'Bali'),
(35,'Donga'),
(35,'Gashaka'),
(35,'Gassol'),
(35,'Ibi'),
(35,'Jalingo'),
(35,'Karim Lamido'),
(35,'Kurmi'),
(35,'Lau'),
(35,'Sardauna'),
(35,'Takum'),
(35,'Ussa'),
(35,'Wukari'),
(35,'Yorro'),
(35,'Zing');

INSERT INTO lgas (state_id, name) VALUES
(36,'Bade'),
(36,'Bursari'),
(36,'Damaturu'),
(36,'Fika'),
(36,'Fune'),
(36,'Geidam'),
(36,'Gujba'),
(36,'Gulani'),
(36,'Jakusko'),
(36,'Karasuwa'),
(36,'Machina'),
(36,'Nangere'),
(36,'Nguru'),
(36,'Potiskum'),
(36,'Tarmuwa'),
(36,'Yunusari'),
(36,'Yusufari');

INSERT INTO lgas (state_id, name) VALUES
(37,'Anka'),
(37,'Bakura'),
(37,'Birnin Magaji/Kiyaw'),
(37,'Bukkuyum'),
(37,'Bungudu'),
(37,'Gummi'),
(37,'Gusau'),
(37,'Kaura Namoda'),
(37,'Maradun'),
(37,'Maru'),
(37,'Shinkafi'),
(37,'Talata Mafara'),
(37,'Tsafe'),
(37,'Zurmi');

-- Total LGAs seeded: 774
